### ISSUE TITLE
view doesn't contain more than 21 ids

### ISSUE THREAD

**Issue by lightem90** [lightem90/testMRMW#10]
when updating a view with a new id of a connected node sometimes some ids are deleted. the printed view never shows more than 21 ids. No idea why. Here it is the output, the program is a bit modified (not exactly like master version)

[output.txt](https://github.com/lightem90/testMRMW/files/11874/output.txt)

**Comment by xit4** [comment]
error is probably in the lines under https://github.com/lightem90/testMRMW/blob/2cbf5ba6410e180a18aba6d2ab93691289f0dcdf/src/NetworkPrimitives/ConnectionManager.java#L267
somewhere between getting an array filling it and reassigning it there is an array.

**Comment by lightem90** [comment]
that lines SHOULD be correct. "Old view" and "New view" print is called in the View constructor as well, I think the issue is there, tonight I'll check. Should be fixed with evening tests

**Comment by lightem90** [comment]
Problem is here: 

https://github.com/lightem90/testMRMW/blob/master/src/com/robustMRMW/FailureDetector.java#L94

Here it is a new output of tonight test, I did a mistake while printing the "new view", tomorrow will be fixed but there are still problems, don't know what's wrong
[output.txt](https://github.com/lightem90/testMRMW/files/12823/output.txt)

**Comment by lightem90** [comment]
For example here:

Received init_ack from node #9
Current node view (in FD): 1/3/4/5/7/8/10/11/12/13/15/16/17/19/20/21/22/24/26/
Current FD value: [3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 19, 20, 21, 22, 24, 26]

after an init_ack is received updateFDforid is called and 1 is removed and 9 is inserted. how can this happend?

**Comment by lightem90** [comment]
fixed with https://github.com/lightem90/testMRMW/commit/32b8b90f458b65e4caba8c533f9959ab55fb8d77
